### ISSUE TITLE
Missing 'new' prefix when invoking a constructor Warnings

### ISSUE THREAD

**Issue by ifandelse** [CondeNast/JSXHint#16]
First - thanks _so much_ for creating this project! (_Internet hugs/high fives/or whatever kudos you're cool with_)

This is primarily a question, to verify that I'm not missing anything. If I leave the `newcap` option set to `true`, it triggers the jshint warnings about not including new when invoking a function that starts with an upper-case letter (which it assumes to be a constructor). It turns out that each line this gets reported on is including another React/JSX component.
For example, a render method like this in a React component:

``` jsx
var component = React.createClass({
    render: function() {
        return <div>
                <span>Hai World:</span>
                <MyChildComponent />
            </div>;
    }
});
```

Would list the `newcap` warning for the line on which `<MyChildComponent />` exists. I can, of course, set `newcap` to `false`, but I wanted to check to make sure that you're aware this happens and to see if perhaps I should be doing something differently?

**Comment by toddself** [comment]
Hey @ifandelse!  Thanks for the props.

This is one of the reasons that I decided to deprecate this software: since I can't always guarantee that the generated code from the JSX Transpiler will be JSHint compliant (especially since it's not a stated goal of the transplier).

The other reason is that JSHint as of version 2.2.0 supports the ability to ignore certain parts of a file when linting:

``` javascript
render: function(){
    return
/* jshint ignore: start */
        <div > and other jsx syntax
/* jshint ignore: end*/
```

If you feel like you still want to run JSHint on your transpiled files (with the hope that your syntax settings match the ones the code generator outputs), you are welcome to fork this project.  Happy to assign the npm module name to you as well!

Thanks!

**Comment by ifandelse** [comment]
@toddself Thanks for the quick reply. I didn't realize you'd deprecated it - my bad. I also didn't realize the new jshint supported the ignore directive - that's a great alternative as well.

**Comment by StoneCypher** [comment]
This is actually a valid objection, because JSHint explicitly implements the JSLint set, which in turn is Crockford's bizarrely religious rule list.  The "newcap" option is the appropriate response.

**Comment by toddself** [comment]
![lol](http://i.imgur.com/wUboltj.png)
:smiley:

**Comment by StoneCypher** [comment]
I agree, this is an old ticket.

I just wanted to make sure that the correct answer was here, because it ranks very highly on Google for the issue.
